/* XPM */
static char * java_xpm[] = {
"20 20 127 2",
"  	c None",
". 	c #D6CBC0",
"+ 	c #DBD5CE",
"@ 	c #D3C9BF",
"# 	c #CFC7BC",
"$ 	c #ADA090",
"% 	c #D9D6CF",
"& 	c #F0EFEC",
"* 	c #F6F6F5",
"= 	c #EDEAE6",
"- 	c #F9FBFB",
"; 	c #FEFFFF",
"> 	c #EEEDE9",
", 	c #E0DDD7",
"' 	c #D5D2C9",
") 	c #E4E1DC",
"! 	c #F3F4F1",
"~ 	c #E0DBD0",
"{ 	c #C3B5A1",
"] 	c #C1B39D",
"^ 	c #C2B6A0",
"/ 	c #CABFAE",
"( 	c #DCD9D1",
"_ 	c #EBE8E4",
": 	c #D6D2CB",
"< 	c #D2CBC2",
"[ 	c #D1C9BE",
"} 	c #D6CEC3",
"| 	c #D7D0C5",
"1 	c #D7D0C4",
"2 	c #DAD4C9",
"3 	c #E0DCD4",
"4 	c #E9E8E3",
"5 	c #DEDDD6",
"6 	c #DAD7D0",
"7 	c #D0CAC1",
"8 	c #D1CABF",
"9 	c #D3CEC4",
"0 	c #D7D3CA",
"a 	c #CECBC4",
"b 	c #E0DFD8",
"c 	c #E4E4DF",
"d 	c #EAECE8",
"e 	c #D5D3CC",
"f 	c #CDC9C0",
"g 	c #D4CEC5",
"h 	c #D7D2C9",
"i 	c #D9D5CE",
"j 	c #C0BDB6",
"k 	c #DCDBD6",
"l 	c #E6E6E1",
"m 	c #ECEEEA",
"n 	c #C8C4BA",
"o 	c #D1CDC4",
"p 	c #E0DDD6",
"q 	c #D3D0C7",
"r 	c #EBE9E5",
"s 	c #FDFDFD",
"t 	c #F1EFEC",
"u 	c #DFDAD2",
"v 	c #E7E4DE",
"w 	c #E1DFDA",
"x 	c #C5C3BE",
"y 	c #E3E1DD",
"z 	c #EAEAE5",
"A 	c #EAE8E3",
"B 	c #CEC9BE",
"C 	c #DFDDD7",
"D 	c #ECEBE8",
"E 	c #E4E2DD",
"F 	c #C8C3B9",
"G 	c #FFFFFF",
"H 	c #FDFEFD",
"I 	c #F3F2F0",
"J 	c #EEE9E5",
"K 	c #F6F3F0",
"L 	c #E6E5E3",
"M 	c #D3D2CF",
"N 	c #E0DEDB",
"O 	c #F3F1ED",
"P 	c #E9E5E0",
"Q 	c #D1CEC6",
"R 	c #DFDED8",
"S 	c #F9F9F8",
"T 	c #DAD7CF",
"U 	c #FDFDFC",
"V 	c #F7F7F5",
"W 	c #E8E9E4",
"X 	c #D4D1C9",
"Y 	c #EFEEEB",
"Z 	c #F1EFED",
"` 	c #EFECE9",
" .	c #E8E5DF",
"..	c #CFCBC2",
"+.	c #D6D5CD",
"@.	c #E5E4DF",
"#.	c #F8F8F7",
"$.	c #DDD9D1",
"%.	c #F7F6F4",
"&.	c #EFF0EE",
"*.	c #D5D3CD",
"=.	c #D9D7CE",
"-.	c #CAC3B5",
";.	c #C9C1B3",
">.	c #CDC4B8",
",.	c #D4CFC6",
"'.	c #BFB7A8",
").	c #D6D4CD",
"!.	c #E7E7E3",
"~.	c #F7F8F6",
"{.	c #F2F2EF",
"].	c #C1B9AD",
"^.	c #AEA292",
"/.	c #D4D0C8",
"(.	c #ECECE7",
"_.	c #F6F7F4",
":.	c #F1F1EC",
"<.	c #E9E7E1",
"[.	c #EDECE6",
"}.	c #EFEDE8",
"|.	c #F1F0EC",
"1.	c #E3E1DA",
"2.	c #CCC6BB",
"3.	c #A39685",
"4.	c #8F7C69",
"5.	c #917E6B",
"6.	c #8D7A67",
"                                        ",
"                                        ",
"                                        ",
"                  .                     ",
"                                        ",
"                                        ",
"              + @ # $                   ",
"          % & * = - ; > , '             ",
"          ) ! ~ { ] ^ / ( _ : &         ",
"          < [ } | 1 2 3 4 5     6       ",
"          7 8 9 0 a b c d e     f       ",
"          7 g h i j k l m n o p         ",
"    q r s t u v w x y z A B C D E       ",
"  F G s H I J K L M N O P Q R z S I     ",
"  T G U V W X A Y Z `  ...+.e @.#.G     ",
"    $.%.&.c *.=.-.;.>.,.'.).!.~.{.].    ",
"        ^./.(._.:.<.[.}.|.1.2.3.        ",
"                4.5.6.                  ",
"                                        ",
"                                        "};
